# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ict/protobuf/db.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ict.protobuf import simulation_pb2 as ict_dot_protobuf_dot_simulation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ict/protobuf/db.proto',
  package='backend.db',
  syntax='proto3',
  serialized_pb=_b('\n\x15ict/protobuf/db.proto\x12\nbackend.db\x1a\x1dict/protobuf/simulation.proto\"c\n\x0c\x44\x61taRequired\x12\n\n\x02id\x18\x01 \x01(\t\x12\x32\n\x05\x62lock\x18\x02 \x01(\x0e\x32#.backend.simulation.SimulationBlock\x12\x13\n\x0bstored_data\x18\x03 \x03(\t\"\xf8\x01\n\x08InitInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x39\n\x0b\x64\x61ta_values\x18\x02 \x03(\x0b\x32$.backend.db.InitInfo.DataValuesEntry\x12\x30\n\x06\x61rrays\x18\x03 \x03(\x0b\x32 .backend.db.InitInfo.ArraysEntry\x1a\x31\n\x0f\x44\x61taValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x02:\x02\x38\x01\x1a@\n\x0b\x41rraysEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12 \n\x05value\x18\x02 \x01(\x0b\x32\x11.backend.db.Array:\x02\x38\x01\"\x17\n\x05\x41rray\x12\x0e\n\x06values\x18\x01 \x03(\x02\"z\n\tStoreData\x12\x15\n\rsimulation_id\x18\x01 \x01(\t\x12\x0f\n\x07node_id\x18\x02 \x01(\t\x12\x16\n\x0e\x61ttribute_name\x18\x03 \x01(\t\x12\x10\n\x08timestep\x18\x04 \x01(\x02\x12\r\n\x05value\x18\x05 \x01(\x02\x12\x0c\n\x04unit\x18\x06 \x01(\tb\x06proto3')
  ,
  dependencies=[ict_dot_protobuf_dot_simulation__pb2.DESCRIPTOR,])




_DATAREQUIRED = _descriptor.Descriptor(
  name='DataRequired',
  full_name='backend.db.DataRequired',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='backend.db.DataRequired.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='block', full_name='backend.db.DataRequired.block', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='stored_data', full_name='backend.db.DataRequired.stored_data', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=167,
)


_INITINFO_DATAVALUESENTRY = _descriptor.Descriptor(
  name='DataValuesEntry',
  full_name='backend.db.InitInfo.DataValuesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='backend.db.InitInfo.DataValuesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='backend.db.InitInfo.DataValuesEntry.value', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=303,
  serialized_end=352,
)

_INITINFO_ARRAYSENTRY = _descriptor.Descriptor(
  name='ArraysEntry',
  full_name='backend.db.InitInfo.ArraysEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='backend.db.InitInfo.ArraysEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='backend.db.InitInfo.ArraysEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=_descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001')),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=354,
  serialized_end=418,
)

_INITINFO = _descriptor.Descriptor(
  name='InitInfo',
  full_name='backend.db.InitInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='backend.db.InitInfo.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data_values', full_name='backend.db.InitInfo.data_values', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='arrays', full_name='backend.db.InitInfo.arrays', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_INITINFO_DATAVALUESENTRY, _INITINFO_ARRAYSENTRY, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=418,
)


_ARRAY = _descriptor.Descriptor(
  name='Array',
  full_name='backend.db.Array',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values', full_name='backend.db.Array.values', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=420,
  serialized_end=443,
)


_STOREDATA = _descriptor.Descriptor(
  name='StoreData',
  full_name='backend.db.StoreData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='simulation_id', full_name='backend.db.StoreData.simulation_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='node_id', full_name='backend.db.StoreData.node_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute_name', full_name='backend.db.StoreData.attribute_name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timestep', full_name='backend.db.StoreData.timestep', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='backend.db.StoreData.value', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='unit', full_name='backend.db.StoreData.unit', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=445,
  serialized_end=567,
)

_DATAREQUIRED.fields_by_name['block'].enum_type = ict_dot_protobuf_dot_simulation__pb2._SIMULATIONBLOCK
_INITINFO_DATAVALUESENTRY.containing_type = _INITINFO
_INITINFO_ARRAYSENTRY.fields_by_name['value'].message_type = _ARRAY
_INITINFO_ARRAYSENTRY.containing_type = _INITINFO
_INITINFO.fields_by_name['data_values'].message_type = _INITINFO_DATAVALUESENTRY
_INITINFO.fields_by_name['arrays'].message_type = _INITINFO_ARRAYSENTRY
DESCRIPTOR.message_types_by_name['DataRequired'] = _DATAREQUIRED
DESCRIPTOR.message_types_by_name['InitInfo'] = _INITINFO
DESCRIPTOR.message_types_by_name['Array'] = _ARRAY
DESCRIPTOR.message_types_by_name['StoreData'] = _STOREDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DataRequired = _reflection.GeneratedProtocolMessageType('DataRequired', (_message.Message,), dict(
  DESCRIPTOR = _DATAREQUIRED,
  __module__ = 'ict.protobuf.db_pb2'
  # @@protoc_insertion_point(class_scope:backend.db.DataRequired)
  ))
_sym_db.RegisterMessage(DataRequired)

InitInfo = _reflection.GeneratedProtocolMessageType('InitInfo', (_message.Message,), dict(

  DataValuesEntry = _reflection.GeneratedProtocolMessageType('DataValuesEntry', (_message.Message,), dict(
    DESCRIPTOR = _INITINFO_DATAVALUESENTRY,
    __module__ = 'ict.protobuf.db_pb2'
    # @@protoc_insertion_point(class_scope:backend.db.InitInfo.DataValuesEntry)
    ))
  ,

  ArraysEntry = _reflection.GeneratedProtocolMessageType('ArraysEntry', (_message.Message,), dict(
    DESCRIPTOR = _INITINFO_ARRAYSENTRY,
    __module__ = 'ict.protobuf.db_pb2'
    # @@protoc_insertion_point(class_scope:backend.db.InitInfo.ArraysEntry)
    ))
  ,
  DESCRIPTOR = _INITINFO,
  __module__ = 'ict.protobuf.db_pb2'
  # @@protoc_insertion_point(class_scope:backend.db.InitInfo)
  ))
_sym_db.RegisterMessage(InitInfo)
_sym_db.RegisterMessage(InitInfo.DataValuesEntry)
_sym_db.RegisterMessage(InitInfo.ArraysEntry)

Array = _reflection.GeneratedProtocolMessageType('Array', (_message.Message,), dict(
  DESCRIPTOR = _ARRAY,
  __module__ = 'ict.protobuf.db_pb2'
  # @@protoc_insertion_point(class_scope:backend.db.Array)
  ))
_sym_db.RegisterMessage(Array)

StoreData = _reflection.GeneratedProtocolMessageType('StoreData', (_message.Message,), dict(
  DESCRIPTOR = _STOREDATA,
  __module__ = 'ict.protobuf.db_pb2'
  # @@protoc_insertion_point(class_scope:backend.db.StoreData)
  ))
_sym_db.RegisterMessage(StoreData)


_INITINFO_DATAVALUESENTRY.has_options = True
_INITINFO_DATAVALUESENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
_INITINFO_ARRAYSENTRY.has_options = True
_INITINFO_ARRAYSENTRY._options = _descriptor._ParseOptions(descriptor_pb2.MessageOptions(), _b('8\001'))
# @@protoc_insertion_point(module_scope)
